# Generated by Django 4.2.15 on 2024-08-19 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atendente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DadosRetirada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('telefone', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EntregaBairro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bairro', models.CharField(max_length=100)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entregador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('telefone', models.IntegerField(blank=True, null=True)),
                ('veiculo', models.CharField(blank=True, max_length=100, null=True)),
                ('placa', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DadosVendaLocal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeClienteMesa', models.CharField(blank=True, max_length=100, null=True)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.novovalor')),
            ],
        ),
        migrations.CreateModel(
            name='DadosEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('telefone', models.IntegerField(blank=True, null=True)),
                ('endereco', models.CharField(blank=True, max_length=100, null=True)),
                ('pontoReferencia', models.CharField(blank=True, max_length=100, null=True)),
                ('bairroPadrao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.entregabairro')),
                ('entregador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.atendente')),
            ],
        ),
    ]
