# Generated by Django 4.2.15 on 2024-08-19 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_atendente_dadosretirada_entregabairro_entregador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='tipo_venda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tipo_venda'),
        ),
    ]
